CREATE TABLE producto (idProducto INT NOT NULL) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
//Modificar la tabla
ALTER TABLE producto RENAME productos;
RENAME TABLE productos to producto, producto to productos;
//Eliminar tabla
DROP TABLE productos;
//COPIA O BACKUP DE UNA ENTIDAD
CREATE TABLE BKP_PRUDUCTOS AS SELECT * FROM PRODUCTOS;
//CAMBIAR EL NOMBRE UNA TABLA
ALTER TABLE BKP_PRODUCTOS RENAME TO PRODUCTOS_1;
AUMENTAR LA LONGITUD A UN ATRIBUTO
ALTER TABLE PRODUCTOS_1 MODIFY NombreProducto VARCHAR2(50);

ROLLBACK;
COMMIT;
